import sys

from helpers.Encoder import Encoder
from helpers.DataWrangler import DataWrangler

sys.path.append('/home/jaro/school/memory_span')
import numpy as np

from elman.preprocessing import getSentenceData
from elman.rnn import Model

"""
word_dim = 8000
hidden_dim = 100
X_train, y_train = getSentenceData('../data/reddit-comments-2015-08.csv', word_dim)
"""

data_string = "bbadcbdacdccaaaacacabdcddadbdbabaabccbbabacaadabdccccdcdaaacbaadcddbbbbbdcbaccdacbcaadabbbcaacbdcccbbabbdcdabdcbdabdadadbabcbbdbcbcdaaaccbacbcbaccaacaddbdaabaaaddcabdcbbbbdccaccbaaccccbcabacadddbbaabdbbcacbbbbdcccbbaaabacdccbcdcacacbdbadaaaacaddcbdcbabdbdcbbddaadcbbbdbbccabdabbabcddcbdaddbbdbbbabddbacddacccbabdcbbbdbbcacaddabaabadbcadbccccdaccbacacabacaadbcaddddbaabbdaabdbcdccdacacbcdacbaccdacbcbdaabcbaaadccdaaabcbbadbbbdddacbcbcdbadcadcdbccdcbccabbcbccbddbbabbaccabbccbdccdabaddacacaddabccdcabdbdbcbdcbdbaccccddcbcdbcddbdcdabbacccdbadaadddcdaabcbaadbbccccbaddcaacdcaacdacbddaddcbdddbbbadabbdbaddacadcdbacbaaddcbacbcaadbaccbacbcdcdddccdbbddbdbaccdcaddcbddbacbcddbdccbbabacaaccdbcbdbadaaaabccccdbcacacbacabcdbcdaabcacbddcabddbaacbbabdaadbbccadcdadcbcbcacbcbbdcbdbcbcbbbaabbdbddccacbccccddddcacbbcddacbcadcbbbddacdaacacbadbcdbcddccccbccacabbacbbaabdcbaccaaadcbddcdabacddaadbbdcdbbacaaabccabcaaacabddabdbbdaadddaabbdbddabdbcadabacbbdcbbbcadaaabbbccbccddbadadaabcaaaddccbccdbcadacdabcbdbacababcaacdcc"

X_train, Y_train = DataWrangler.get_training_data(data_string)

np.random.seed(10)



rnn = Model(999, 30)

losses = rnn.train(X_train, Y_train, learning_rate=0.05, nepoch=3, evaluate_loss_after=1)

print(rnn.predict(Encoder.encode_character('a')))
